version: '3.8'
services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/ad-backend:latest
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - .:/app
